version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: exampl
    volumes:
      - ./dump.sql:/dump.sql
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432