version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: user_api
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./dump.sql:/dump.sql
    ports:
      - 5432:5432